### ISSUE TITLE
current_scopes only works after apply_scopes

### ISSUE THREAD

**Issue by GuyPaddock** [plataformatec/has_scope#72]
It may seem obvious to others, but it took me a bit to realize that `current_scopes` will return an empty hash unless `apply_scopes` has been called.

I was hoping that `current_scopes` would return the scopes that would be applied before calling `apply_scopes`.

**Comment by carlosantoniodasilva** [comment]
Yes, `apply_scopes` is the one that figures out which scopes will be applied, and populates `current_scopes` on the go.

Is there any particular reason you'd want to know the scopes _before_ they are applied? I imagine applying the scopes should never be a problem, since we're dealing with in memory objects, not triggering the queries until the very last, so technically calling `apply_scopes` if you need `current_scopes` should not be costly.

In any case, I don't actually see this as an issue but as an implementation detail, so I'm giving it a close. I'll be happy to reopen if we agree at some point that it is an issue, so please feel free to continue the discussion. Thanks!

**Comment by GuyPaddock** [comment]
Sorry, I meant to clarify that the docs should indicate that it only has a value after calling `apply_scopes`. So, this was a docs issue.

**Comment by carlosantoniodasilva** [comment]
Right, I see.. Well, right now the docs we have are:

README:

> You can retrieve all the scopes applied in one action with current_scopes method. In the last case, it would return: { :featured => true, :by_degree => "phd" }.

[Method](https://github.com/plataformatec/has_scope/blob/df1fb68e437ea7df7499d6f73d9568b6d09c8e50/lib/has_scope.rb#L196):

>   # Returns the scopes used in this action.

We are happy to merge a PR if you'd like to improve on top of these. Thanks!

**Comment by ausminternet** [comment]
Here is an example from me, where I would need `current_scope` to be available before using `apply_scopes`. I have the "new Task"-form at my index page, and therefore I need to render 'index' again, if any errors occur on creation:

```
class TasksController < ApplicationController
  has_scope :scopeB
  has_scope :scopeA

  def index
    # need to be called for current_scopes to be populated
    apply_scopes(current_user.tasks.all)

    @task = Task.new
    index_tasks
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to :back
    else
      index_tasks
      render action: 'index'
    end

  private
    def index_tasks
      if current_scopes.empty?
        @tasks = current_user.tasks.where(parent_id: nil)
      else
        @tasks = apply_scopes(current_user.tasks.all)
      end
    end
end
```

**Comment by carlosantoniodasilva** [comment]
@ausminternet I'm thinking your scenario could be handled with something like this:

```ruby
@tasks = apply_scopes(current_user.tasks)

if current_scopes.empty?
  @tasks = @tasks.where(parent_id: nil)
end
```

This way, you always call `apply_scopes` before actually asking for the `current_scopes`, and you only need to call it once (no need to call it inside the index action as it is right now).

Would that work for your use case?

Thanks.

**Comment by ausminternet** [comment]
That is working for me, thx!

**Comment by carlosantoniodasilva** [comment]
:+1:
